$('button.random-fact').on('click', function(e){
  randomFact = getRand(allFactsArray)
  $('#fact').html(randomFact);
});

$('button.general-fact').on('click', function(e){
  $('#fact').html(getRand(factsArray));
});

$('button.yasha-fact').on('click', function(e){
  $('#fact').html(getRand(yashaFactsArray));
});

var getRand = function(array) {
  return array[Math.floor(Math.random() * array.length)];
};

var yashaFactsArray = [
  "Yasha is afraid of needles.",
  "Yasha has destructive pinky toes.",
  "Yasha loves soda.",
  "Yasha named his first nephew Cletus the Fetus as a placeholder name.",
  "Yasha used to sumo wrestle.",
  "Yasha loves eating meat."
];

var factsArray = [
  "The human heart creates enough pressure to squirt blood 30 feet (9 m).",
  "The United States has never lost a war in which mules were used.",
  "When snakes are born with two heads, they fight each other for food.",
  "Women are 37% more likely to go to a psychiatrist than men are.",
  "\"Goodbye\" came from \"God bye\" which came from \"God be with you\".",
  "A skunk's smell can be detected by a human a mile away.",
  "Canadian researchers have found that Einstein's brain was 15% wider than normal.",
  "Every year about 98% of the atoms in your body are replaced.",
  "On average, there are 178 sesame seeds on each McDonalds BigMac bun.",
  "There are two credit cards for every person in the United States.",
  "When you die your hair still grows for a couple of months.",
  "7.5 million toothpicks can be created from a cord of wood.",
  "According to suicide statistics, Monday is the favored day for self-destruction.",
  "Every human spent about half an hour as a single cell.",
  "It took Leo Tolstoy six years to write \"War & Peace\".",
  "Paul Revere rode on a horse that belonged to Deacon Larkin.",
  "The fist product to have a bar code was Wrigleys gum.",
  "The king of hearts is the only king without a moustache.",
  "The plastic things on the end of shoelaces are called aglets.",
  "The surface area of an average-sized brick is 79 cm squared.",
  "1 in 5,000 north Atlantic lobsters are born bright blue.",
  "A lion's roar can be heard from five miles away.",
  "The Australian $5 to $100 notes are made of plastic.",
  "The average person makes about 1,140 telephone calls each year.",
  "You burn more calories sleeping than you do watching TV.",
  "American car horns beep in the tone of F.",
  "The elephant is the only animal with 4 knees.",
  "The international telephone dialing code for Antarctica is 672.",
  "The most common name in the world is Mohammed.",
  "Cats sleep 16 to 18 hours per day.",
  "Elephants are the only mammals that can't jump.",
  "St. Stephen is the patron saint of bricklayers.",
  "The Neanderthal's brain was bigger than yours is.",
  "World Tourist day is observed on September 27.",
  "Diet Coke was only invented in 1982.",
  "Charlie Brown's father was a barber.",
  "Children grow faster in the springtime.",
  "Karoke means \"empty orchestra\" in Japanese.",
  "Odontophobia is the fear of teeth.",
  "February is Black History Month.",
  "Stressed is Desserts spelled backwards.",
  "Cats can hear ultrasound.",
  "The pancreas produces Insulin.",
  "\"Arachibutlphobia\" is the fear of peanut butter sticking to the roof of your mouth.",
  "\"Challenger Deep\" is the deepest point on Earth and can hold 25 Empire State Buildings end to end.",
  "\"Disco\" means \"I learn\" in Latin.",
  "\"O\" is the oldest letter of the alphabet, dating back to 3000 B.C.",
  "\"Q\" is the only letter in the alphabet not appearing in the name of any U.S. state.",
  "\"Way\" is the most frequently used noun in the English language.",
  "1.3 billion pounds of peanuts are produced in Georgia each year.",
  "1/4 of the bones in your body are in your feet.",
  "100% recyclable, old newspapers are great for washing windows.",
  "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
  "13 percent of the world's tea comes from Kenya.",
  "2nd Street is the most common street name in the United States; First Street is the 6th most common.",
  "454 U.S. dollar bills weigh exactly one pound.",
  "75% of people wash from top to bottom in the shower.",
  "90% of all garlic consumed in the U.S. comes from Gilroy, CA.",
  "A baboon is a variety of lemon.",
  "A baby caribou can outrun its mother at 3 days old.",
  "A ball of glass will bounce higher than a ball of rubber.",
  "A banana is a giant herb.",
  "A bee has five eyelids.",
  "A cat has 32 muscles in each ear.",
  "A cat's lower jaw cannot move sideways.",
  "A chalkboard eraser is one of the best ways to wipe a foggy windshield.",
  "A chameleon shoots out its tongue to catch prey at speeds faster than a fighter jet.",
  "A compass needle does not point directly north.",
  "A crocodile cannot move its tongue.",
  "A cubic mile of fog is made up of less than a gallon of water.",
  "A cucumber consists of 96% water.",
  "A dog's average body temperature is 101 degrees Fahrenheit.",
  "A duck can't walk without bobbing its head.",
  "A duck has three eyelids.",
  "A duck's quack doesn't echo.",
  "A female kangaroo is called a flyer.",
  "A fifteen-year-old boy invented earmuffs in 1873.",
  "A flea can jump 30,000 times without stopping.",
  "A full moon is nine times brighter than a half moon.",
  "A full-grown tree produces enough oxygen to support a family of four.",
  "A gallon of water weighs 8.34 pounds.",
  "A goldfish's attention span is three seconds.",
  "A group of a dozen or more cows is called a 'flink.'",
  "A group of cats is called a clowder.",
  "A group of geese on the ground is a gaggle, a group of geese in the air is a skein.",
  "A group of goats is called a trip.",
  "A group of jellyfish is called a smack.",
  "A group of twelve or more cows is called a flink.",
  "A honey bee can fly at 15mph.",
  "A housefly hums in the key of F.",
  "A human brain weighs about three pounds.",
  "A hummingbird weighs less than a penny.",
  "A hummingbird's heart beats 1,400 times a minute.",
  "A jackrabbit can travel more than 12 feet in one hop.",
  "A jellyfish is 95% water.",
  "A jiffy is an actual time measurement equaling 1/100th of a second.",
  "A kangaroo can jump 30 feet.",
  "A lemon contains more sugar than a strawberry.",
  "A male cricket's ear is located on the tibia of its leg.",
  "A male firefly's light is twice as bright as a female's.",
  "A male kangaroo is called a boomer.",
  "A manned rocket can reach the moon in less time than it took a stagecoach to travel the length of England.",
  "A mile on the ocean and a mile on land are not the same distance.",
  "A nautical mile is 800 feet longer than a land mile.",
  "A one-day weather forecast requires about 10 billion math calculations.",
  "A one-minute kiss burns 26 calories.",
  "A Pelican can hold more food in its beak than its belly.",
  "A pigeon's feathers are heavier than its bones.",
  "A pineapple is neither an apple or a pine. It is, in fact, a large berry.",
  "A polar bear cannot be seen by an infrared camera, due to its transparent fur.",
  "A queen bee can lay 800-1,500 eggs per day.",
  "A rainbow can only be seen in the morning or late afternoon.",
  "A rhinoceros horn is made of compacted hair.",
  "A sea lemon is a mollusk that feeds on sponges.",
  "A single coffee tree produces only about a pound of coffee beans per year.",
  "A snail breathes through its foot.",
  "A sneeze travels out of your mouth at over 100 miles an hour.",
  "A spider's silk is stronger than steel.",
  "A stamp shaped like a banana was once issued in the country of Tonga.",
  "A strand from the web of a golden spider is as strong as a steel wire of the same size.",
  "A strawberry is not an actual berry but a banana is.",
  "A tankless water heater uses half the energy of a standard model.",
  "A teaspoon contains 120 drops of water.",
  "A ten gallon hat holds less than one gallon of liquid.",
  "A tiger's night vision is six times better than a human's.",
  "A tune that gets stuck in your head is called an earworm.",
  "A turkey can run at 20 mph.",
  "A twit is the technical term for a pregnant goldfish.",
  "About 18 percent of animal owners share their bed with their pet.",
  "About 80 women go into labor on NYC subways every year.",
  "About 85% of the world's population is right-handed.",
  "About half of all Americans are on a diet on any given day.",
  "Abraham Lincoln was the tallest U.S. President at 6'4\". James Madison was the shortest at 5'4\".",
  "Add up opposing sides of a dice cue and you'll always get seven.",
  "Africa is divided into more countries than any other continent.",
  "After working out, it takes 5 hours for your body temperature to return to normal.",
  "Alaska has more caribou than people.",
  "Alaska has the highest percentage of people who walk to work.",
  "Alaska is the most eastern and western state in the U.S.",
  "Alaska was bought from Russia for about 2 cents an acre.",
  "All dog breeds except chow-chows have black lips to prevent them from getting sunburned.",
  "All lemons are harvested by hand.",
  "All polar bears are left-handed.",
  "All porcupines float in water.",
  "All scorpions glow.",
  "Almonds are part of the peach family.",
  "America's 1st roller coaster was built in 1827 to carry coal from a mine to boats below.",
  "Americans spend more than $630 million a year on golf balls.",
  "Americans, on average, eat 18 acres of pizza a day.",
  "Among North Atlantic lobsters, 1 in 5,000 is born bright blue.",
  "An alligator can go through 3,000 teeth in a lifetime.",
  "An ant can lift 50 times its own weight.",
  "An ant's sense of smell is stronger than a dog's.",
  "An average of three billion cups of tea are consumed daily worldwide.",
  "An egg that is fresh will sink in water, but a stale one won't.",
  "An electric eel can release a charge powerful enough to start 50 cars.",
  "An ostrich's brain is smaller than its eye.",
  "Ancient Egyptians believed the \"vein of love\" ran from the third finger on the left hand to the heart.",
  "Animals that lay eggs don't have belly buttons.",
  "Antarctica has as much ice as the Atlantic Ocean has water.",
  "Antarctica holds 90% of the world's fresh water.",
  "Antarctica is the driest, coldest, windiest, and highest continent on earth.",
  "Antarctica is the only continent with no owls.",
  "Apples, peaches and raspberries are all members of the rose family.",
  "Approximately 16,500 people in the U.S. go by the last name Lemon.",
  "Armadillos have four babies at a time and they are always all the same sex.",
  "Astronauts actually get taller when in space.",
  "At 5 feet, the whooping crane is the tallest bird in North America.",
  "At birth a human has 350 bones, but only 206 bones when full grown.",
  "At birth, a Dalmation is always pure white.",
  "At room temperature, the average air molecule travels at the speed of a rifle bullet.",
  "Atlantic salmon are capable of leaping 15 feet high.",
  "August has the highest percentage of births.",
  "Australia is the only continent without an active volcano.",
  "Baboons were once trained by Egyptians to wait on tables.",
  "Baking soda makes a great scouring cleanser, and it's naturally chemical-free.",
  "Bald eagles can swim using a stroke similar to the butterfly stroke.",
  "Bamboo (the world's tallest grass) can grow up to 90cm in a day.",
  "Bamboo can grow over three feet per day.",
  "Bamboo can grow three feet in one day.",
  "Bamboo makes up 99 percent of a panda's diet.",
  "Barbie's full name is Barbara Millicent Roberts.",
  "Beavers can hold their breath for 45 minutes under water.",
  "Beavers have orange teeth.",
  "Beavers were once the size of bears.",
  "Bees are born fully grown.",
  "Bees' wings beat 11,400 times per minute.",
  "Before 1687 clocks were made with only an hour hand.",
  "Before mercury, brandy was used to fill thermometers.",
  "Before Thomas Jefferson took office people bowed to the president, rather than shaking his hand.",
  "Besides humans, elephants are the only animals that can be taught to stand on their head.",
  "Blackboard chalk contains no chalk.",
  "Bloodhounds can track a man by smell for up to 100 miles.",
  "Borborygmi is the noise that your stomach makes when you are hungry.",
  "Bowling pins need to tip over a mere 7 1/2 degrees to fall down.",
  "Brain waves can be used to power an electric train.",
  "Brain waves can power an electric train.",
  "Britain was the first country to register a patent on polyester.",
  "Broadway is one of the longest streets in the world. It is 150 miles long.",
  "Broccoli is the only vegetable that is also a flower.",
  "Butterflies taste with their hind feet.",
  "Butterflies were formerly known by the name Flutterby.",
  "Buzz Aldrin was one of the first men on the moon. His mother's maiden name was also Moon.",
  "California and Arizona grow approximately 95% of the fresh lemons in the U.S.",
  "Caller ID is illegal in California.",
  "Camel's milk does not curdle.",
  "Camels have three eyelids.",
  "Camels have three eyelids.",
  "Canada has the longest coastline of any country in the world.",
  "Candles will burn longer and drip less if they are placed in the freezer a few hours before using.",
  "Cape May is the oldest seashore resort in America.",
  "Caterpillars have over 2,000 muscles.",
  "Cats can hear ultrasound.",
  "Cats have 2 sets of vocal cords: one for purring and one for meowing.",
  "Cats have over 100 vocal chords.",
  "Chameleons can move both their eyes in different directions at the same time.",
  "Chewing gum was invented in New York City in 1870 by Thomas Adams.",
  "Chewing gum while peeling onions will prevent you from crying.",
  "Children grow faster during springtime.",
  "Children grow faster in the spring.",
  "Children have more taste buds than adults.",
  "China only has one time zone.",
  "Chinese is the most spoken language in the world.",
  "Christopher Columbus brought the first lemon seeds to America.",
  "Clearwater, Florida has the highest rate of lightning strikes per capita in the US.",
  "Cleveland, OH is home to the first electric traffic lights.",
  "Cold water weighs less than hot water.",
  "Colors like red, yellow and orange make you hungry.",
  "Connecticut was the first state to pass a Lemon Law in 1982.",
  "Cows do not have upper front teeth.",
  "Cows give more milk when they listen to music.",
  "Cranberries are sorted for ripeness by bouncing them.",
  "Dairy cows drink up to 50 gallons of water per day.",
  "David Rice Atchison was President of the United States for only one day.",
  "Despite its hump, a camel has a straight spine.",
  "Detroit has the greatest number of registered bowlers in the U.S.",
  "Dieting by not eating will actually make your body start conserving calories as fat.",
  "Dim lights reduce your appetite.",
  "Dogs can make about 10 sounds, cats make about 100.",
  "Dolphins can jump up to 20 feet in the air.",
  "Dolphins sleep with one eye open.",
  "Double Dutch jump rope is considered a cross-training sport.",
  "Dragonflies have six legs but can't walk.",
  "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
  "During the Boston Tea Party, 342 chests of tea were thrown into the harbor.",
  "Each year, the average American eats about 15 pounds of apples.",
  "Each year, the average person walks the distance from NY to Miami.",
  "Elephants are capable of swimming 20 miles per day.",
  "Elephants are the only mammals that can't jump.",
  "Elephants only sleep two hours a day.",
  "Eleven of the 50 U.S. states are named after an actual person.",
  "Eleven percent of people in the world are left-handed.",
  "Emus and kangaroos cannot walk backward.",
  "Endocarp is the edible pulp inside a lemon.",
  "Every hour more than one billion cells in the body must be replaced.",
  "Every state except Maine, Alaska, and Hawaii is home to at least one species of venomous snake.",
  "Every ton of recycled paper saves about 17 trees.",
  "Farmington, Maine celebrates Chester Greenwood Day to honor the inventor of earmuffs.",
  "Ferret comes from the Latin word for little thief.",
  "Fish can drown.",
  "Fish cough.",
  "Fish have eyelids.",
  "Flamingos can only eat with their heads upside down.",
  "Flamingos turn pink from eating shrimp.",
  "Flying fish leap out of the water at 20 mph or more, and can glide for over 500 feet.",
  "For every human being in the world there is approximately one chicken.",
  "Forty percent of America's population lives within a one-day drive to Philadelphia.",
  "Forty-six percent of leisure visitors to downtown New York City come from outside the United States.",
  "Four Corners, AZ, is the only place where a person can stand in 4 states at the same time.",
  "Franklin Roosevelt was related to 5 U.S. Presidents by blood and 6 by marriage.",
  "French author Michel Thayer published a 233 page novel which has no verbs.",
  "Fresh apples float because 25 percent of their volume is air.",
  "Fresh cranberries can be bounced like a rubber ball.",
  "Frogs cannot swallow with their eyes open.",
  "Frogs never drink.",
  "Frowning burns more calories than smiling.",
  "Galapagos turtles can take up to three weeks to digest a meal.",
  "George Washington took the oath of office in New York City in 1789.",
  "George Washington was the only unanimously elected President.",
  "Giraffes can lick their own eyes.",
  "Giraffes have no vocal chords.",
  "Googol is a number (1 followed by 100 zeros).",
  "Grapes are the most popular fruit in the world.",
  "Great Falls, Montana, is the windiest city in the U.S.",
  "Greyhounds can reach speeds of 45 miles per hour.",
  "Grizzly bears run as fast as the average horse.",
  "Harry S. Truman's middle name is S.",
  "Harry Truman was the last U.S. President to not have a college degree.",
  "Hawaii has its own time zone.",
  "Hawaii is further south than Florida.",
  "Hawaii is moving toward Japan at the rate of almost 4 inches per year.",
  "Hawaii is the only state with one school district.",
  "Hawaii is the only U.S. state never to report a temperature of zero degrees F or below.",
  "Hawaii is the only U.S. state that grows coffee.",
  "Hawaii is the only US state that grows coffee.",
  "Heat, not sunlight, ripens tomatoes.",
  "Heavier, not bigger lemons, produce more juice.",
  "Hippos can open their mouths 180 degrees.",
  "Holland is the only country with a national dog.",
  "Honeybees are the only insects that create a form of food for humans.",
  "Honeybees have hair on their eyes.",
  "Honeybees navigate by using the sun as a compass.",
  "Horseback riding can improve your posture.",
  "Human eyes have over two million working parts.",
  "Hybrid cars produce up to 75% less pollution than other vehicles.",
  "If a sheep and a goat mate the offspring is called a geep.",
  "If done perfectly, any Rubick's Cube combination can be solved in 17 turns.",
  "If there are two full moons in a month, the second one is called a blue moon.",
  "If you doubled one penny every day for 30 days, you would have $5,368,709.",
  "If you drive from Los Angeles to Reno, NV, you will be heading west.",
  "If you had 1 billion dollars and spent 1 thousand dollars a day, it would take you 2,749 years to spend it all.",
  "If you keep a goldfish in a dark room it will eventually turn white.",
  "If you put all the streets in New York City in a straight line, they would stretch to Japan.",
  "If you shake a can of mixed nuts, the larger nuts will rise to the top.",
  "In 1634, tulip bulbs were a form of currency in Holland.",
  "In 1859, 24 rabbits were released in Australia. Within 6 years, the population grew to 2 million.",
  "In 1860, Abraham Lincoln grew a beard at the suggestion of an 11-year-old girl.",
  "In 1878, the first telephone book ever issued contained only 50 names.",
  "In 1900, 1/3 of all automobiles in New York City were powered by electricity.",
  "In 1908, the first lollipop-making machine started in New Haven, CT.",
  "In 1926, the first outdoor mini-golf courses were built on rooftops in NYC.",
  "In 1985, the fastest bicyclist was clocked at 154 mph.",
  "In 2003, a 6-year-old from Naples, FL was ticketed for not having a permit for her lemonade stand.",
  "In a year, the average person walks four miles making his or her bed.",
  "In Albania, nodding your head means no and shaking your head means yes.",
  "In Ancient Greece throwing an apple to a woman was considered a marriage proposal.",
  "In ancient Rome, lemons were used as an antidote to all poisons.",
  "In Athens, Greece, a driver's license can be taken away by law if the driver is deemed either unbathed or poorly dressed.",
  "In Germany the shhh sound means hurry up.",
  "In one day, a full-grown oak tree expels 7 tons of water through its leaves.",
  "In some cultures' telling of Snow White, the dwarves are thieves.",
  "In Texas, it is illegal to graffiti someone's cow.",
  "In the average lifetime, a person will walk the equivalent of 5 times around the equator.",
  "In the game Monopoly, the properties are named after streets in Atlantic City.",
  "In the Middle Ages, chicken soup was considered an aphrodisiac.",
  "In the U.S. a pig has to weigh more than 180 lbs to be called a hog.",
  "In the U.S., all interstate highways that run east to west are even-numbered.",
  "In the U.S., there are about 15,000 vacuum cleaner-related accidents each year.",
  "In Youngstown Ohio, it is against the law to run out of gas.",
  "India has a Bill of Rights for cows.",
  "India has more English speakers than the United States.",
  "International tug of war rules state that the rope must be over 100-feet long.",
  "It costs the U.S. government 2.5 cents to produce a quarter.",
  "It is against the law to put pretzels in bags in Philadelphia.",
  "It is estimated that the world's oceans contain 10 billion tons of gold.",
  "It is illegal for a portrait of a living person to appear on U.S. postage stamps.",
  "It is impossible to sneeze with your eyes open.",
  "It is not possible to tickle yourself.",
  "It is possible to lead a cow up stairs but not down.",
  "It takes an interaction of 72 muscles to produce human speech.",
  "It takes more water to fill a bathtub than it does to enjoy a nice, warm shower.",
  "It took Leonardo da Vinci 12 years to paint the lips of Mona Lisa.",
  "It took the first man to walk around the world four years, three months and 16 days to complete his journey.",
  "Jack is the most common name in nursery rhymes.",
  "Jack-O-Lanterns were originally made out of turnips.",
  "John Adams was the only President to be defeated by his Vice President, Thomas Jefferson.",
  "Jousting is the official sport in the state of Maryland.",
  "Jousting is the official sport of Maryland.",
  "Jupiter spins so fast that there is a new sunrise nearly every 10 hours.",
  "Kangaroos can't walk backwards.",
  "Karate originated in India.",
  "Ketchup was once sold as a medicine.",
  "Knots come out easier if you sprinkle talcum powder on them.",
  "Koala and humans are the only animals with unique fingerprints.",
  "Koalas only drink water in extreme heat or drought.",
  "Lake Superior is the world's largest lake.",
  "Lemon sharks can give birth to about 36 babies at one time.",
  "Lemon wood is carved into chess pieces.",
  "Lemons are more acidic than vinegar.",
  "Lemons ripen after you pick them, but oranges do not.",
  "Leonardo da Vinci could draw with one hand while writing with the other.",
  "Leonardo da Vinci discovered that a tree's rings reveal its age.",
  "Less than 2% of the water on Earth is fresh.",
  "Licking a stamp burns 10 calories.",
  "Lifejackets used to be filled with sunflower seeds for flotation.",
  "Like fingerprints, everyone's tongue print is different.",
  "Lizards communicate by doing push-ups.",
  "Lobsters can live up to 50 years.",
  "Long Beach Island was once frequented by pirates.",
  "Long Island is the largest island in the Continental U.S.",
  "Louisiana is home to over 80% of the world's crayfish.",
  "Maine is the only state with a one-syllable name.",
  "Maine produces more toothpicks than any other state in the U.S.",
  "Male moose shed their antlers every winter and grow a new pair the next year.",
  "Manhattan is the only borough in New York City that doesn't have a Main Street.",
  "Manhattan Island was once home to as many different species as Yellowstone National Park.",
  "Manhattan was the first capital of the United States.",
  "Manufacturing recycled goods uses up to 95% less energy than using raw materials.",
  "Many butterflies and moths are able to taste with their feet.",
  "Men get hiccups more than women.",
  "Meteorologists claim they're right 85% of the time.",
  "Mexican jumping beans jump to get out of sunlight.",
  "Miami installed the first ATM for rollerbladers.",
  "Mongolians invented lemonade around 1299 A.D.",
  "More babies are born at night than during the day.",
  "More Siberian tigers live in zoos than in the wild.",
  "More than 180 countries celebrate Earth Day together every April 22nd.",
  "Mosquitoes are attracted to people who just ate bananas.",
  "Mosquitoes have 47 teeth.",
  "Most cats don't like lemonade.",
  "Most elephants weigh less than the tongue of a blue whale.",
  "Most Koala bears sleep about 22 hours a day.",
  "Most lipstick contains fish scales.",
  "Most rechargeable batteries can be recharged up to 1,000 times.",
  "Mount Everest rises a few millimeters every year.",
  "Mount Katahdin in Maine is the first place in the U.S. to get sunlight each morning.",
  "Mount Whitney, the highest mountain in the continental United States, and Zabriskie Point, the lowest point in the United States, are less than eighty miles apart.",
  "Mountain goats aren't actually goats. They are antelopes.",
  "Mt. Everest has grown one foot over the last 100 years.",
  "Napoleon suffered from a fear of cats.",
  "Nearly 9,000 people injure themselves with a toothpick each year.",
  "Neckties were first worn in Croatia, which is why they were called cravats.",
  "New Jersey is home to the world's first drive-in movie theater.",
  "New York City has 722 miles of subway track.",
  "New York City is made up of 50 islands.",
  "New York City's public school students represent about 188 different countries.",
  "New York taxi drivers collectively speak 60 languages.",
  "New York was the first state to require cars to have license plates.",
  "No only child has been a U.S. President.",
  "No piece of paper can be folded more than seven times.",
  "No two lip impressions are the same.",
  "No word in the English language rhymes with month.",
  "Of all the trees in Australia, 75% are eucalyptus.",
  "Of the 92 counties in Indiana, only 5 observe daylight savings time.",
  "Ohio is the only U.S. state that does not have a rectangular flag.",
  "On average a human will spend up to 2 weeks kissing in his/her lifetime.",
  "On average a man spends about five months of his life shaving.",
  "On average a strawberry has 200 seeds on it.",
  "On average, a laptop uses half as much energy as a desktop computer.",
  "On average, you'll spend a year of your life looking for misplaced objects.",
  "On Valentine's Day, there is no charge to get married in the Empire State Building's chapel.",
  "One acre of peanuts will make 30,000 peanut butter sandwiches.",
  "One alternative title that had been considered for NBC's hit \"Friends\" was \"Insomnia CafÃ©.\"",
  "One brow wrinkle is the result of 200,000 frowns.",
  "One in six doctors in America was trained in Philadelphia.",
  "One lemon tree will produce about 1,500 lemons a year.",
  "One lump of sugar is equivalent to three feet of sugar cane.",
  "One out of every eight residents in the U.S. lives in California.",
  "Only female mosquitoes bite.",
  "Only male fireflies can fly.",
  "Only male turkeys gobble.",
  "Oregon has more ghost towns than any other US city.",
  "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
  "Over 1 million Earths would fit inside the Sun.",
  "Over 50 percent of your body heat is lost through your head and neck.",
  "Over half of the world's geysers are found in Yellowstone National Park.",
  "Owls are one of the only birds who can see the color blue.",
  "Oysters can change from one gender to another and back again.",
  "Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic.",
  "Panda bears eat up to 16 hours a day.",
  "Pearls dissolve in vinegar.",
  "Penguins can jump 6 feet.",
  "Penguins have an organ above their eyes that converts seawater to fresh water.",
  "Pennsylvania is misspelled on the Liberty Bell.",
  "People don't sneeze when they are asleep because the nerves involved in the sneeze reflex are also resting.",
  "Philadelphia was the first capital of the United States.",
  "Pigeons have been trained by the U.S. Coast Guard to spot people lost at sea.",
  "Pigs get sunburned.",
  "Pigs were banished from Philadelphia's city streets in 1710.",
  "Pilates stretches your muscles, improving your posture and helping you appear taller.",
  "Pistol shrimp can make a noise loud enough to break glass.",
  "Place a slice of bread in the storage container to keep cookies soft when storing.",
  "Place an apple in the bag with your potatoes to keep them from budding.",
  "Plants, like humans, can run a fever if they are sick.",
  "Playing in a marching band is considered moderate exercise.",
  "Pluto takes 248 years to orbit the sun once.",
  "Poison Ivy is not Ivy and Poison Oak is not an Oak. They are both part of the Cashew family.",
  "Polar bear fur is transparent, not white.",
  "Polar bears can smell a seal from 20 miles away.",
  "Pomology is the study of fruit.",
  "Popcorn was invented by the American Indians.",
  "Porcupines each have 30,000 quills.",
  "Potatoes have more chromosomes than humans.",
  "Pound cake got its name from the original recipe which called for a pound of butter.",
  "President Warren G. Harding once lost white house china in a poker game.",
  "President William McKinley had a pet parrot that he named \"Washington Post.\"",
  "President William Taft weighed over 300 lbs and once got stuck in the white house bathtub.",
  "Raindrops can fall as fast as 20 miles per hour.",
  "Recycled paper is made using 40% less energy than normal paper.",
  "Refrigerating apples can help them last up to 10 times longer than those left at room temperature.",
  "Relative to size, the tongue is the strongest muscle in the human body.",
  "Replacing your car's air filter can improve gas mileage by 10 percent.",
  "Right handed people tend to chew food on the right side and lefties chew on the left.",
  "Rinsing bacon under cold water before frying can reduce the amount it shrinks by almost 50 percent.",
  "Rubber bands last longer when refrigerated.",
  "Sailors once thought wearing gold earrings improved eyesight.",
  "Seals sleep only one and a half minutes at a time.",
  "Shakespeare invented the word assassination and bump.",
  "Shrimp can only swim backward.",
  "Six-year-olds laugh an average of 300 times a day. Adults only laugh 15 to 100 times a day.",
  "Slugs have four noses.",
  "Smelling apples and/or bananas can help you lose weight.",
  "Smile more - every two thousand frowns creates one wrinkle.",
  "Snails can sleep for up to three years.",
  "Snoopy is the most common dog name beginning with the letter S.",
  "Some bears build nests in trees for sunbathing and resting.",
  "Some dinosaurs were as small as chickens.",
  "Some violins contain 70 separate pieces of wood.",
  "Sound travels quicker in water than in air.",
  "South Carolina is home to the first tea farm in the U.S.",
  "Spiny lobsters migrate in groups of 50 or more, forming a conga line on the ocean floor.",
  "Squids can have eyes the size of a volleyball.",
  "Steel is 100% recyclable.",
  "Stepping out for a walk every day can actually help you sleep better at night.",
  "Storm clouds hold about 6 trillion raindrops.",
  "Strawberries are the only fruits whose seeds grow on the outside.",
  "Strawberries contain more vitamin C than oranges.",
  "Swimming pools in the U.S. contain enough water to cover San Francisco.",
  "Taft was the heaviest U.S. President at 329lbs; Madison was the smallest at 100lbs.",
  "Tennessee banned the use of a lasso to catch fish.",
  "Tennessee was previously named Franklin after Benjamin Franklin.",
  "Termites eat through wood two times faster when listening to rock music!",
  "Texas is the only state that permits residents to cast absentee ballots from space.",
  "Thailand means \"Land of the Free.\"",
  "The \"high five\" was introduced by a professional baseball player in 1977.",
  "The \"lemon yellow\" crayon was introduced in 1949 and retired in 1990.",
  "The \"silk\" of a spider is stronger than steel threads of the same diameter.",
  "The 1st public message to be transmitted via Morse code was \"A patient waiter is no loser.\"",
  "The 4th Earl of Sandwich invented the sandwich so he could eat and gamble at the same time.",
  "The act of chewing an apple is a more efficient way to stay awake than caffeine.",
  "The amount of concrete used in the Hoover Dam could build a highway from New York to California.",
  "The archer fish can spit water up to 7 feet to shoot down bugs from overhanging leaves.",
  "The area code in Cape Canaveral, Fl, is 321.",
  "The average American walks 18,000 steps a day.",
  "The average American will eat 35,000 cookies in his/her lifetime.",
  "The average bar of soap lasts twice as long as a bottle of body wash.",
  "The average cat can jump 5 times as high as its tail is long.",
  "The average housefly lives for one month.",
  "The average human dream lasts only 2 to 3 seconds.",
  "The average human eats 8 spiders in his/her lifetime while sleeping.",
  "The average human produces 10,000 gallons of saliva in a lifetime.",
  "The average koala sleeps 22 hours each day.",
  "The average lead pencil can draw a line 35 miles long or write roughly 50,000 English words.",
  "The average person falls asleep in seven minutes.",
  "The average person makes 1,140 phone calls per year.",
  "The average person spends 2 weeks over his/her lifetime waiting for a traffic light to change.",
  "The average person spends about 2 years on the phone in a lifetime.",
  "The average person takes 23,000 breaths a day.",
  "The average person uses 150 gallons of water per day for personal use.",
  "The average raindrop falls at seven mph.",
  "The average smell weighs 760 nanograms.",
  "The average speed of a housefly is 4.5 mph.",
  "The average turtle can't reproduce until it's 25 years old.",
  "The average woman is 5 inches shorter than the average man.",
  "The average women consumes six pounds of lipstick in her lifetime.",
  "The Basenji is the only type of dog that does not bark.",
  "The beaver is the official animal of Canada.",
  "The biggest pig in recorded history weighed almost one ton.",
  "The blue whale's heart is the size of a small car.",
  "The brain operates on the same amount of power as a 10-watt light bulb.",
  "The bullfrog is the only animal that never sleeps.",
  "The bumblebee bat is the smallest mammal on Earth. It weighs less than a penny.",
  "The can opener was invented 48 years after the can.",
  "The Capitol building in Washington, D.C. has 365 steps to represent every day of the year.",
  "The Caspian Sea is actually a lake.",
  "The center of some golf balls contain honey.",
  "The chicken is the closest living relative of Tyrannosaurus Rex.",
  "The city of Los Angeles has three times more automobiles than people.",
  "The coldest city in the U.S. is International Falls, Minnesota.",
  "The common garden worm has five pairs of hearts.",
  "The deepest place in the ocean is about seven miles deep.",
  "The dot over the letter i is called a tittle.",
  "The dots on a domino are called pips.",
  "The dragonfly can reach speeds of up to 36 mph.",
  "The East Antarctic Ice Sheet is as thick as the Alps Mountains are high.",
  "The Empire State Building has 73 elevators.",
  "The eye makes movements 50 times every second.",
  "The fastest growing nail is on the middle finger.",
  "The fastest recorded speed of a racehorse was over 43 mph.",
  "The fastest served ball in tennis was clocked at 154 mph in 1963.",
  "The fear of vegetables is called lachanophobia.",
  "The first ballpoint pens were sold in 1945 for $12.00.",
  "The first bike was called a hobbyhorse.",
  "The first country to use postcards was Austria.",
  "The first food eaten in space by a U.S. astronaut was applesauce.",
  "The first human-made object to break the sound barrier was a whip.",
  "The first jukebox was located in San Francisco in 1899.",
  "The first lighthouse to use electricity was the Statue of Liberty in 1886.",
  "The first lollipop was invented in Connecticut.",
  "The first MTV video was \"Video Killed the Radio Star\" by the Buggles.",
  "The first penny had the motto \"Mind your own business.\"",
  "The first person crossed Niagara Falls by tightrope in 1859.",
  "The first person in the U.S. arrested for speeding was a NYC cab driver.",
  "The first sailing boats were built in Egypt.",
  "The first sport to be filmed was boxing in 1894.",
  "The first traffic light was in use in London in 1868, before the advent of cars.",
  "The first TV network kids show in the U.S. was \"Captain Kangaroo.\"",
  "The first TV remote control, introduced in 1950, was called Lazy Bones.",
  "The first TV show ever to be put into reruns was \"The Lone Ranger.\"",
  "The first TV soap opera debuted in 1946.",
  "The first TV toy commercial aired in 1946 for Mr. Potato Head.",
  "The first typewriter was called the \"literary piano.\"",
  "The first vacuum was so large, it was brought to a house by horses.",
  "The first VCR was made in 1956 and was the size of a piano.",
  "The game of basketball was first played using a soccer ball and two peach baskets.",
  "The giant panda can eat up to 83 lbs of bamboo a day.",
  "The great white shark can go up to three months between meals.",
  "The Hawaiian alphabet only has 12 letters.",
  "The height of the Eiffel Tower varies by as much as 6 inches depending on the temperature.",
  "The highest denomination issued by the U.S. was the 100,000 dollar bill.",
  "The hippopotamus has the capability to remain underwater for as long as five minutes.",
  "The human brain is about 80% water.",
  "The human brain takes up 2% of human body weight but uses 20% of its energy.",
  "The human jaw can generate a force up to 200 pounds on the molars.",
  "The hummingbird is the only bird that can fly backwards.",
  "The indentation in the middle of the area between the nose and the upper lip is called the philtrum.",
  "The infinity sign is called a lemniscate.",
  "The jaguar, the largest cat in the Western Hemisphere, once lived all over the southern US.",
  "The Japanese word \"judo\" means \"the gentle way.\"",
  "The largest ball of twine in the US weighs over 17,000.",
  "The largest cheesecake ever made weighed 57,508 lbs.",
  "The largest dog litter was 23 puppies.",
  "The largest fish is the whale shark - it can be over 50 feet long and weigh two tons.",
  "The largest hailstone ever recorded in the U.S. was 17.5 inches around.",
  "The largest pumpkin ever grown weighed 1,061 lbs.",
  "The last letter to be added to our alphabet was J.",
  "The legs of bats are too weak to support their weight, so they hang upside down.",
  "The Lemon-Yellow Tree Frog is only active in the darkness of night.",
  "The Library of Congress has 600 miles of shelves.",
  "The lifespan of a taste bud is 10 days.",
  "The Lollipop was named after one of the most famous Racehorses in the early 1900s, Lolly Pop.",
  "The longest one syllable word is \"screeched.\"",
  "The mango is the most consumed fruit in the world.",
  "The Mayflower only held 102 People.",
  "The medical term for writer's cramp is graphospasm.",
  "The Mona Lisa has no eyebrows.",
  "The most common name for a pet goldfish is 'Jaws.'",
  "The most popular ice cream flavor is vanilla.",
  "The most popular pet name in the United States is 'Max.'",
  "The most sensitive parts of the body are the mouth and the fingertips.",
  "The most used letters in the English language are E, T, A, O, I and N.",
  "The most widely eaten fruit in America is the banana.",
  "The mouth of the Statue of Liberty is 3 feet wide.",
  "The muzzle of a lion is like a fingerprint - no two lions have the same pattern of whiskers.",
  "The name for the space between your eyebrows is \"nasion.\"",
  "The name of the city we call Bangkok is 115 letters long in the Thai language.",
  "The National Park Service manages over 350 parks on 80 million acres of public land.",
  "The Nickname of President Hayes's wife was \"Lemonade Lucy.\"",
  "The number 1 or the word One appears on the dollar bill 16 times.",
  "The number of times a cricket chirps in 15 seconds, plus 37, will give you the current air temperature.",
  "The number sign # is called an octothorpe.",
  "The official color of California's Golden Gate Bridge is International Orange.",
  "The official state gem of Washington is petrified wood.",
  "The oil in cashews helps prevent tooth decay.",
  "The oldest known animal was a tortoise, which lived to be 152 years old.",
  "The oldest living animal ever found was a 405 year-old clam, named Ming by researchers.",
  "The only bird that can swim and not fly is a penguin.",
  "The only bird who can see the color blue is the owl.",
  "The only cactus plantation in the world is in Mississippi.",
  "The only continent without reptiles or snakes is Antarctica.",
  "The only food that does not spoil is honey.",
  "The only food that does not spoil is honey.",
  "The only insect that can turn its head is a praying mantis.",
  "The only jointless bone in the body is in your throat.",
  "The only lizard that has a voice is the Gecko.",
  "The only one-syllabled U.S. state is Maine.",
  "The optimum depth of water in a birdbath is two and a half inches.",
  "The original Cinderella was Egyptian and wore fur slippers.",
  "The original name of Nashville, Tennessee was Big Salt Lick.",
  "The original recipe for chocolate contained chili powder instead of sugar.",
  "The peach was the first fruit to be eaten on the moon.",
  "The pineapple is a very big berry.",
  "The planet Saturn has a density lower than water. It would float if placed in water.",
  "The plastic things on the end of shoelaces are called aglets.",
  "The pomegranate is one of the oldest fruits known to man.",
  "The popsicle was invented in 1905 by an 11-year-old boy.",
  "The pound sign, or #, is called an octothorp.",
  "The pupils in goats' eyes are rectangular.",
  "The quartz crystal in your wristwatch vibrates 32,768 times a second.",
  "The raised bump reflectors on U.S. roads are named \"Botts dots.\"",
  "The ridges on the sides of coins are called reeding or milling.",
  "The roadrunner chases after its prey at a blurring speed of up to 25 mph.",
  "The Sahara Desert stretches farther than the distance from California to New York.",
  "The sail fish has been clocked at speeds of over 60 miles per hour.",
  "The San Francisco cable cars are the only mobile national monument.",
  "The Saturn V moon rocket consumed 15 tons of fuel per second.",
  "The shoreline at Wildwood grows almost 100 feet per year.",
  "The side of a hammer is called a cheek.",
  "The smallest county in America is New York County, better known as Manhattan.",
  "The smallest mammal in the world is the bumblebee bat, which weighs less than a penny.",
  "The speed limit in NYC was eight mph in 1895.",
  "The spotted skunk does a handstand to warn off its enemies before it sprays its stench.",
  "The square dance is the official dance of the state of Washington.",
  "The standard Chinese typewriter has 1,500 characters.",
  "The starfish is the only animal that can turn its stomach inside out.",
  "The state of Florida is bigger than England.",
  "The state of Maine has 62 lighthouses.",
  "The state of Tennessee was originally called Franklin.",
  "The Statue of Liberty features 7 points in her crown- one for each of the continents.",
  "The Statue of Liberty wears a size 879 sandal.",
  "The Statue of Liberty's nose is four feet six inches long.",
  "The strike note of The Liberty Bell is E flat.",
  "The sun evaporates about a trillion tons of water a day.",
  "The T-rex's closest living relative is the chicken.",
  "The tallest man was 8 ft. 11 in.",
  "The temperature of the sun can reach up to 15 million degrees Fahrenheit.",
  "The term 007 was derived from 20007, the home zip code of many Washington, D.C. agents.",
  "The term rookies comes from a Civil War term, reckie, which was short for recruit.",
  "The tongue is the fastest healing part of the body.",
  "The top of the Empire State Building was originally built as a place to anchor blimps.",
  "The typewriter was invented in Milwaukee, WI in 1867.",
  "The U.S. is the largest country named after an actual person (Amerigo Vespucci).",
  "The Valley of Square Trees in Panama is the only known place in the world where trees have rectangular trunks.",
  "The Venus flytrap can eat a whole cheeseburger.",
  "The watermelon seed-spitting world record is about 70 feet.",
  "The watersheds that supply water to New York City are roughly the size of Delaware.",
  "The weight of the moon is 81 billion tons.",
  "The White House was originally called the President's Palace. It became The White House in 1901.",
  "The Wildwood Boardwalk extends nearly two miles and has more than 70,000 wooden planks.",
  "The woodpecker can hammer wood up to 16 times per second.",
  "The word \"facetious\" features all the vowels in alphabetical order.",
  "The word \"purple\" does not rhyme with any other word in the English language.",
  "The world's biggest pyramid is not in Egypt, but in Mexico.",
  "The world's first escalator was built in Coney Island, NY, in 1896.",
  "The world's largest silver nugget (1,840 lbs) was found in 1894 near Aspen, Colorado.",
  "The world's termites outweigh the world's humans 10 to 1.",
  "The year that read the same upside down was 1961. That won't happen again until 6009.",
  "The youngest U.S. president to be in office was Theodore Roosevelt at age 42.",
  "The ZIP in the ZIP code stands for Zone Improvement Plan.",
  "Theodore Roosevelt had a pet bear while in office.",
  "Theodore Roosevelt was the only president who was blind in one eye.",
  "There are 118 ridges on the edge of a United States dime.",
  "There are 119 grooves on the edge of a quarter.",
  "There are 18 different animal shapes in the animal cracker zoo.",
  "There are 293 ways to make change for a dollar.",
  "There are 336 dimples on a regulation American golf ball.",
  "There are 63,360 inches in a mile.",
  "There are approximately 7,000 feathers on an eagle.",
  "There are approximately 9,000 taste buds on your tongue.",
  "There are more chickens than people in the world.",
  "There are more doughnut shops per capita in Canada than in any other country.",
  "There are more French restaurants in New York City than in Paris.",
  "There are more saunas than cars in Finland.",
  "There are more species of fish in the Amazon river than in the Atlantic Ocean.",
  "There are more telephones than people in Washington, D.C.",
  "There are more than 30,000 diets on public record.",
  "There are one million ants to every human in the world.",
  "There are over 2,000 different species of cactuses.",
  "There are over 61,000 pizzerias in the U.S.",
  "There are seven letters that look the same upside down as right side up.",
  "There are towns named Sandwich in Illinois and Massachusetts.",
  "There is a museum of strawberries in Belgium.",
  "There is a ranch in Texas that is bigger than the entire state of Rhode Island.",
  "There is a town called \"Big Ugly\" in West Virginia.",
  "There is a town called Jackpot in Nevada.",
  "There is a town called Jersey Shore in Pennsylvania.",
  "There is a town in Alaska called Chicken.",
  "There is a town in South Dakota named Tea.",
  "There is an underground mushroom in Oregon that measures 3.5 miles across.",
  "Thomas Edison coined the word \"hello\" and introduced it as a way to answer the phone.",
  "Thomas Jefferson invented the coat hanger.",
  "Three out of every six Americans live within fifty miles of where they were born.",
  "Tigers have striped skin, not just striped fur.",
  "To clean paint off your hands, use olive oil - it softens the paint and makes it easy to remove.",
  "To fix a button about to fall off, dab a little clear nail polish over the threads holding it on.",
  "To keep an ice cream cone from dripping, stuff a miniature marshmallow into the bottom of the cone.",
  "To make a zipper slide up and down more smoothly, rub a bar of soap over the teeth.",
  "To remove crayon marks from walls, use a hairdryer to heat the wax.",
  "To take lumps out of a bag of sugar, place it in the refrigerator for 24 hours.",
  "To temporarily revive your ballpoint pen, dip the tip into hot water for a few seconds.",
  "Today's \"modern\" wrestling moves have been seen in tomb drawings from ancient Egypt.",
  "Top-performing companies are called \"blue chips\" after the costliest chips in casinos.",
  "Tsiology is anything written about tea.",
  "Tug-of-war was an Olympic sport in the early 1900's.",
  "Turning the faucet off while brushing your teeth can save up to 5 gallons of water.",
  "TV dinners originated in the Artic.",
  "Twinkle Twinkle Little Star was composed by Mozart when he was five years old.",
  "Twins have a very high occurrence of left handedness.",
  "Two trees can create enough oxygen for a family of four.",
  "U.S. paper currency isn't made of paper - it's actually a blend of cotton and linen.",
  "Ulysses Simpson Grant once got a $20.00 fine for speeding on his horse.",
  "Underwater hockey is played with a 3-pound puck.",
  "Unlike your housecat, the Siberian tiger actually loves to swim!",
  "Until the 19th century, solid blocks of tea were used as money in Siberia.",
  "Until the nineteenth century, solid blocks of tea were used as money in Siberia.",
  "Vanilla is used to make chocolate.",
  "Vermont is the only New England state without a seacoast.",
  "Vultures can fly for six hours without flapping their wings.",
  "When the moon is directly overhead you weigh slightly less.",
  "When thirsty, a camel can drink 25 gallons of water in less than three minutes.",
  "While chopping onions, hold a piece of bread between your lips to keep your eyes from watering.",
  "Wild camels once roamed Arizona's deserts.",
  "Wildlife Forever has helped plant 132,420 trees in America since its founding in 1987.",
  "William Shakespeare was born and died on the same day: April 23.",
  "Wipe the leaves of your plants with the soft inside of a banana skin to bring up shine and remove dust.",
  "Wisconsin has points located farther east than parts of Florida.",
  "With an average life expectancy of 81.2 years, the people of Okinawa, Japan live the longest.",
  "Women blink nearly twice as much as men.",
  "Women's hearts beat faster than men's hearts.",
  "Wrapping rubber bands around the ends of hangers can prevent clothes from slipping off.",
  "You blink over 10,000,000 times a year.",
  "You breathe in about 13 pints of air every minute.",
  "You burn 20 calories an hour chewing gum.",
  "You burn more calories sleeping than watching TV.",
  "You burn more calories sleeping than you do watching television.",
  "You can tell which day a loaf of bread was baked by the color of its plastic twist tag.",
  "You don't have to be a lawyer to be a Supreme Court Justice.",
  "You exhale air at 15 m.p.h.",
  "You have to play ping-pong for 12 hours to lose one pound.",
  "You share your birthday with at least 9 million other people in the world.",
  "You transfer more germs shaking hands than kissing.",
  "You will burn about 7% more calories walking on hard dirt than on pavement.",
  "You would weigh less on the top of a mountain than at sea level.",
  "Your big toe only has 2 bones and the rest have 3.",
  "Your breathing rate increases when you start to type.",
  "Your eye expands up to 45% when looking at something pleasing.",
  "Your skull is made up of 29 different bones."
]

var allFactsArray = factsArray.concat(yashaFactsArray);
